### ISSUE TITLE
Great work. 

### ISSUE THREAD

**Issue by animesh-garg** [omarrayyann/MujocoAR#2]
This is a great effort in open sourcing a teleop device. 
We do however recommend that you refer to 
- https://roboturk.stanford.edu/
- https://github.com/UT-Austin-RobIn/telemoma/blob/main/telemoma/human_interface/mobile_phone.py

It would be good to add pointers to these efforts

**Comment by omarrayyann** [comment]
Hi @animesh-garg, thanks for the heads-up! I wasn’t aware of these, but I’ll definitely add a section in the README file about them.
