### ISSUE TITLE
Not host not receiving messages when phone says connected and sending poses 

### ISSUE THREAD

**Issue by Kongx231** [omarrayyann/MujocoAR#5]
My phone says connected and sending poses but the host never receives the messages.
```
[INFO] MujocoARConnector Starting on port PORTNUMBER...
[INFO] MujocoARConnector Started. Details: 
[INFO] IP Address: IPADDRESS
[INFO] Port: PORTNUMBER
```

What is expected is the host to say:
```
[INFO] Application connected
```

**Comment by Kongx231** [comment]
The issue is from my firewall blocking the incoming messages. The solution is to allow your firewall to listen to through the port that was created with:
```
sudo ufw allow PORTNUMBER/tcp
```

**Comment by omarrayyann** [comment]
@Kongx231 Thanks for flagging the issue.
